[package]
name = "hab-common-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "*", features = ["extra-traits", "parsing"] }
proc-macro2 = "*"
quote = "*"
