[hab]
plan_path = "components/hab"
paths = [
  "components/builder-api-client/*",
  "components/builder-depot-client/*",
  "components/common/*",
  "components/sup-client/*",
  "components/sup-protocol/*",
]

[hab-backline]
plan_path = "components/backline"

[hab-bintray-publish]
plan_path = "components/bintray-publish"
paths = [
  "studio/build-docker-image.sh",
]

[hab-eventsrv]
plan_path = "components/eventsrv/habitat"
paths = [
  "components/eventsrv-protocol/*",
  "components/eventsrv/*",
  "support/ci/builder-base-plan.sh",
]

[hab-launcher]
plan_path = "components/launcher/habitat"
paths = [
  "components/launcher/*",
  "components/launcher-protocol/*",
  "support/ci/builder-base-plan.sh",
]

[hab-plan-build]
plan_path = "components/plan-build"

[hab-studio]
plan_path = "components/studio"

[hab-sup]
plan_path = "components/sup"
paths = [
  "components/builder-depot-client/*",
  "components/butterfly/*",
  "components/common/*",
  "components/eventsrv-client/*",
  "components/launcher-client/*",
  "components/sup-protocol/*",
]

[hab-pkg-aci]
plan_path = "components/pkg-aci"

[hab-pkg-export-docker]
plan_path = "components/pkg-export-docker"
paths = [
  "components/common/*",
  "components/hab/*",
]

[hab-pkg-export-kubernetes]
plan_path = "components/pkg-export-kubernetes"
paths = [
  "components/common/*",
  "components/hab/*", # because pkg-export-docker depends on it
  "components/pkg-export-docker/*",
]

[hab-pkg-export-helm]
plan_path = "components/pkg-export-helm"
paths = [
  "components/common/*",
  "components/hab/*", # because pkg-export-docker depends on it
  "components/pkg-export-docker/*",
  "components/pkg-export-kubernetes/*",
]

[hab-pkg-export-tar]
plan_path = "components/pkg-export-tar"
paths = [
  "components/common/*",
  "components/hab/*",
]

# NOTE: cfize has a dependency on hab-pkg-dockerize, but we are
# *explicitly not building* `hab-pkg-dockerize` any more. Read more at
# components/pkg-dockerize/README.md
[hab-pkg-cfize]
plan_path = "components/pkg-cfize"

[hab-pkg-mesosize]
plan_path = "components/pkg-mesosize"

[hab-pkg-tarize]
plan_path = "components/pkg-tarize"
