[hab]
plan_path = "components/hab"
paths = [
  "components/builder-api-client/*",
  "components/core/*",
  "components/common/*",
  "components/http-client/*",
  "components/sup-client/*",
  "components/sup-protocol/*",
]

[hab-backline]
plan_path = "components/backline"

[hab-launcher]
plan_path = "components/launcher/habitat"
paths = [
  "components/core/*",
  "components/common/*",
  "components/launcher/*",
  "components/launcher-protocol/*",
  "support/ci/builder-base-plan.sh",
]

[hab-plan-build]
plan_path = "components/plan-build"

[hab-plan-build-ps1]
plan_path = "components/plan-build-ps1"

[hab-studio]
plan_path = "components/studio"

[hab-sup]
plan_path = "components/sup"
paths = [
  "components/builder-api-client/*",
  "components/butterfly/*",
  "components/common/*",
  "components/core/*",
  "components/hab/*",
  "components/launcher-client/*",
  "components/sup-protocol/*",
]

[hab-pkg-export-container]
plan_path = "components/pkg-export-container"
paths = [
  "components/common/*",
  "components/core/*",
  "components/hab/*",
]

[hab-pkg-export-tar]
plan_path = "components/pkg-export-tar"
paths = [
  "components/common/*",
  "components/core/*",
  "components/hab/*",
]

[simple-hooks]
plan_path = "test/fixtures/plans/simple-hooks"

[test-probe]
plan_path = "test-services/test-probe"

[supplemental-group-tester]
plan_path = "test-services/supplemental-group-tester"

[health-check-performance-00]
plan_path = "test/fixtures/health-check-performance/health-check-performance-00"
[health-check-performance-01]
plan_path = "test/fixtures/health-check-performance/health-check-performance-01"
[health-check-performance-02]
plan_path = "test/fixtures/health-check-performance/health-check-performance-02"
[health-check-performance-03]
plan_path = "test/fixtures/health-check-performance/health-check-performance-03"
[health-check-performance-04]
plan_path = "test/fixtures/health-check-performance/health-check-performance-04"
[health-check-performance-05]
plan_path = "test/fixtures/health-check-performance/health-check-performance-05"
[health-check-performance-06]
plan_path = "test/fixtures/health-check-performance/health-check-performance-06"
[health-check-performance-07]
plan_path = "test/fixtures/health-check-performance/health-check-performance-07"
[health-check-performance-08]
plan_path = "test/fixtures/health-check-performance/health-check-performance-08"
[health-check-performance-09]
plan_path = "test/fixtures/health-check-performance/health-check-performance-09"
[health-check-performance-10]
plan_path = "test/fixtures/health-check-performance/health-check-performance-10"
[health-check-performance-11]
plan_path = "test/fixtures/health-check-performance/health-check-performance-11"
[health-check-performance-12]
plan_path = "test/fixtures/health-check-performance/health-check-performance-12"
[health-check-performance-13]
plan_path = "test/fixtures/health-check-performance/health-check-performance-13"
[health-check-performance-14]
plan_path = "test/fixtures/health-check-performance/health-check-performance-14"
