
image: Visual Studio 2017

cache:
  - c:\cargo\registry
  - c:\cargo\git
  - c:\projects\habitat\target

branches:
  only:
    - master
    - ^(\d+\.)?(\d+\.)?(\d+)$

init:
  - git config --global core.eol lf
  - mkdir c:\cargo
  - mkdir c:\multirust
  - SET PATH=c:\cargo\bin;%PATH%

clone_folder: c:\projects\habitat

environment:
  CI: true
  CARGO_HOME: "c:\\cargo"
  RUSTUP_HOME: "c:\\multirust"
  CARGO_TARGET_DIR: "c:\\projects\\habitat\\target"
  RUSTUP_USE_HYPER: 1
  CARGO_HTTP_CHECK_REVOKE: false
  HAB_WINDOWS_STUDIO: true
  BINTRAY_USER: chef-releng-ops
  BINTRAY_KEY:
    secure: KGpNfhM18alwGRviNGcMUStNMw3W2u002bf38+fs+mt9wf+4BGGuiUMKtu7Nrs8i
  HAB_AUTH_TOKEN:
    secure: /deSCNJcZdHrtFNJ3zl4zgTjUs+AjT3MStKYbikPLa0anFOS7f4RydFV5cER/mamh5b2sDT2IVASK1uc5SRzE/LTNbcTvspontu9Kbu8to4LEyk4R/MGYpYRHImcVmKHo8zAs7lqp1zx7gJu+TLYi24RfWDQOu4M8WEX4CzFAtcLn2B21obLEehqp6vO6xUXDSTY3WeFfEoPfL3DUUo6BsWNgm68lvGcif6fGt/bw+g=
  ORIGIN_KEY:
    secure: T03FGJrevgQSlLfkc0mDaIkRyfu0/ci6+ryDnSqrezAmbtTayisHStac1yS4/96fMQmyfPYpGP5tMtvjuyw0cplUAUEtXarcK8CgatwnE+t7c9sjpBWgKfSE3wLOiDla
  HAB_CRYPTO_KEY:
    secure: ClumTYe8anMpdAb9ehrDURcO72ufvegDrweI7h+mBODkdlYkW6SzaCFbXbwUgbNCI4bDVQNw3N9/yhU3DUJ3vwmyLRHh/J5JR9aChxJJwYlwRSdVmdTA+G6EgRdEv259

  matrix:
    - hab_build_action: "test;build"
      hab_components: "builder-api-client;common;sup;pkg-export-docker;pkg-export-tar"

    - hab_build_action: "package"
      hab_exe_version: "%24latest"
      hab_components: "hab;plan-build-ps1;studio;sup;pkg-export-docker;pkg-export-tar;bintray-publish"

    - hab_build_action: "package"
      hab_exe_version: "%24latest"
      hab_components: "launcher"

build_script:
  - ps: Update-AppveyorBuild -Version "$((gc -raw ./VERSION).trim())-$((Get-Date).ToString('yyyyMMddHHmmss'))"
  - c:\projects\habitat\support\ci\appveyor.bat

artifacts:
  - path: 'results\*.hart'

  - path: 'results\*.zip'
    name: HabCLI

  - path: 'results\prod\*.zip'
    name: HabProdCLI

  - path: 'results\prod\*.nupkg'
    name: HabProdChoco

deploy:
- provider: BinTray
  username: chef-releng-ops
  api_key:
    secure: KGpNfhM18alwGRviNGcMUStNMw3W2u002bf38+fs+mt9wf+4BGGuiUMKtu7Nrs8i
  subject: habitat
  explode: true
  repo: unstable
  package: hab-x86_64-windows
  publish: true
  artifact: HabCLI
  on:
    branch: master

- provider: BinTray
  username: chef-releng-ops
  api_key:
    secure: KGpNfhM18alwGRviNGcMUStNMw3W2u002bf38+fs+mt9wf+4BGGuiUMKtu7Nrs8i
  subject: habitat
  explode: true
  repo: stable
  package: hab-x86_64-windows
  publish: false
  artifact: HabProdCLI
  on:
    appveyor_repo_tag: true

- provider: NuGet
  server: https://push.chocolatey.org/
  api_key:
    secure: Ux8ZU3v6CNRegF1FBY4Q/ie+Rufn/uSMlqiC95H7jc8nZo4ldUXBuHoVmpbep/Tb
  skip_symbols: true
  artifact: HabProdChoco
  on:
    appveyor_repo_tag: true
