[profile.release]
debug = true

[workspace]
members = [
  "components/builder-api-client",
  "components/butterfly",
  "components/butterfly-test",
  "components/common",
  "components/eventsrv",
  "components/eventsrv-client",
  "components/eventsrv-protocol",
  "components/hab",
  "components/launcher",
  "components/launcher-client",
  "components/launcher-protocol",
  "components/pkg-export-docker",
  "components/pkg-export-helm",
  "components/pkg-export-kubernetes",
  "components/pkg-export-tar",
  "components/sup",
  "components/sup-client",
  "components/sup-protocol",
]

# To test local changes to the core crate, uncomment the following and then
# run `cargo update`. If the core repo isn't in the same directory as the
# habitat repo, you may need to adjust the paths.
# [patch."https://github.com/habitat-sh/core.git"]
# habitat_core = {path = "../core/components/core"}
# habitat_win_users = {path = "../core/components/win-users"}
