[workspace]
members = [
  "components/builder-admin",
  "components/builder-api",
  "components/builder-api-client",
  "components/builder-core",
  "components/builder-db",
  "components/builder-depot",
  "components/builder-depot-client",
  "components/builder-graph",
  "components/builder-http-gateway",
  "components/builder-jobsrv",
  "components/builder-originsrv",
  "components/builder-protocol",
  "components/builder-router",
  "components/builder-scheduler",
  "components/builder-sessionsrv",
  "components/builder-worker",
  "components/butterfly",
  "components/butterfly-test",
  "components/common",
  "components/core",
  "components/eventsrv",
  "components/eventsrv-client",
  "components/hab",
  "components/hab-butterfly",
  "components/http-client",
  "components/launcher",
  "components/launcher-client",
  "components/launcher-protocol",
  "components/net",
  "components/op",
  "components/sup"
]
