[package]
name = "bldr"
version = "0.2.0"
authors = ["Adam Jacob <adam@chef.io>", "Jamie Winsor <reset@chef.io>", "Fletcher Nichol <fnichol@chef.io>"]
exclude = ["plans/**/*"]

[lib]
name = "bldr"
path = "src/bldr/lib.rs"

[[bin]]
name = "bldr"
doc = false

[[test]]
name = "functional"

[dependencies]
docopt = "*"
rustc-serialize = "*"
log = "*"
env_logger = "*"
ansi_term = "*"
gpgme = "*"
hyper = "*"
tempdir = "*"
toml = "*"
regex = "*"
libc = "*"
url = "*"
fnv = "*"
iron = "*"
router = "*"
time = "*"
uuid = "*"
utp = "*"
rmp = "*"
rmp-serialize = "*"

[dependencies.wonder]
path = "./vendor/wonder"

[dependencies.mustache]
git = "https://github.com/adamhjk/rust-mustache"
branch = "fallback_on_missing_extension"

[profile.release]
lto = true
