[package]
name = "habitat_core"
version = "0.0.0"
authors = ["Adam Jacob <adam@chef.io>", "Jamie Winsor <reset@chef.io>", "Fletcher Nichol <fnichol@chef.io>", "Joshua Timberman <joshua@chef.io>", "Dave Parfitt <dparfitt@chef.io>", "Steven Murawski <smurawski@chef.io>"]
workspace = "../../"
build = "build.rs"

[build-dependencies]
base64 = "*"
gcc = "0.3"

[dependencies]
ansi_term = "*"
clippy = {version = "*", optional = true}
base64 = "*"
errno = "*"
hex = "*"
lazy_static = "*"
libarchive = "*"
libc = "*"
# JW: Temporarily use master branch of git until serde 1.0+ is available in crate release
libsodium-sys = "0.0.16"
log = "*"
rand = "*"
regex = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
# JW: Temporarily use master branch of git until serde 1.0+ is available in crate release
sodiumoxide = "0.0.16"
time = "*"
toml = { version = "*", default-features = false }
typemap = "*"
url = "*"

[target.'cfg(not(windows))'.dependencies]
users = "*"

[target.'cfg(windows)'.dependencies.habitat_win_users]
git = "https://github.com/habitat-sh/habitat.git"
branch = "jb/remove-builder"

[target.'cfg(windows)'.dependencies]
crypt32-sys = "*"
ctrlc = "*"
kernel32-sys = "*"
userenv-sys = "*"
widestring = "*"
winapi = "0.2"

[dev-dependencies]
hyper = "0.10"
tempdir = "*"

[features]
default = []
functional = []
