[package]
name = "habitat_api_client"
version = "0.0.0"
authors = ["Josh Black <jblack@chef.io>"]
workspace = "../../"

[dependencies]
broadcast = "*"
chrono = "*"
clippy = {version = "*", optional = true}
# Pending upgrade activities in https://github.com/habitat-sh/core/issues/72
hyper = "0.10"
hyper-openssl = "*"
log = "*"
pbr = "*"
rand = "*"
regex = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
tee = "*"
url = "*"

[dependencies.habitat_core]
git = "https://github.com/habitat-sh/core.git"

[dependencies.habitat_http_client]
git = "https://github.com/habitat-sh/core.git"
