[package]
name = "habitat_api_client"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
workspace = "../../"

[dependencies]
broadcast = "*"
chrono = "*"
env = "*"
habitat_core = { path = "../core" }
habitat_http_client = { path = "../http-client" }
log = "*"
pbr = "*"
rand = "*"
regex = "*"
reqwest = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
tee = "*"
url = "*"
