# For postgresql.conf settings, see
# http://www.postgresql.org/docs/9.5/static/config-setting.html
#
data_directory = "/opt/bldr/svc/postgresql/data"
hba_file = "/opt/bldr/svc/postgresql/config/pg_hba.conf"
ident_file = "/opt/bldr/svc/postgresql/config/pg_ident.conf"
external_pid_file = "/opt/bldr/svc/postgresql/var/postgresql.pid"
listen_addresses = "*"
port = 5432
max_connections = 100
superuser_reserved_connections = 3
unix_socket_directories = "/tmp"
unix_socket_group = ""
unix_socket_permissions = "0777"
bonjour = "off"
bonjour_name = ""
authentication_timeout = "1min"
ssl = "off"
ssl_ciphers = "HIGH:MEDIUM:+3DES:!aNULL"
ssl_prefer_server_ciphers = "on"
ssl_ecdh_curve = "prime256v1"
ssl_cert_file = "/opt/bldr/svc/postgresql/config/server.crt"
ssl_key_file = "/opt/bldr/svc/postgresql/config/server.key"
ssl_ca_file = ""
ssl_crl_file = ""
password_encryption = "on"
db_user_namespace = "off"
row_security = "on"
krb_server_keyfile = ""
krb_caseins_users = "off"
tcp_keepalives_idle = 0
tcp_keepalives_interval = 0
tcp_keepalives_count = 0
shared_buffers = "128MB"
huge_pages = "try"
temp_buffers = "8MB"
max_prepared_transactions = 0
work_mem = "4MB"
maintenance_work_mem = "64MB"
autovacuum_work_mem = "-1"
max_stack_depth = "2MB"
dynamic_shared_memory_type = "posix"
temp_file_limit = "-1"
max_files_per_process = 1000
shared_preload_libraries = ""
vacuum_cost_delay = 0
vacuum_cost_page_hit = 1
vacuum_cost_page_miss = 10
vacuum_cost_page_dirty = 20
vacuum_cost_limit = 200
bgwriter_delay = "200ms"
bgwriter_lru_maxpages = 100
bgwriter_lru_multiplier = 2.0
effective_io_concurrency = 1
max_worker_processes = 20
wal_level = "hot_standby"
fsync = "on"
synchronous_commit = "on"
wal_sync_method = "fsync"
full_page_writes = "on"
wal_compression = "off"
wal_log_hints = "off"
wal_buffers = -1
wal_writer_delay = "200ms"
commit_delay = 0
commit_siblings = 5
checkpoint_timeout = "5min"
max_wal_size = "1GB"
min_wal_size = "80MB"
checkpoint_completion_target = 0.9
checkpoint_warning = "30s"
archive_mode = "on"
archive_command = "cd ."
archive_timeout = 0
max_wal_senders = 20
wal_keep_segments = 0
wal_sender_timeout = "60s"
max_replication_slots = 20
track_commit_timestamp = "off"
synchronous_standby_names = ""
vacuum_defer_cleanup_age = 0
hot_standby = "on"
max_standby_archive_delay = "30s"
max_standby_streaming_delay = "30s"
wal_receiver_status_interval = "10s"
hot_standby_feedback = "off"
wal_receiver_timeout = "60s"
wal_retrieve_retry_interval = "5s"
enable_bitmapscan = "on"
enable_hashagg = "on"
enable_hashjoin = "on"
enable_indexscan = "on"
enable_indexonlyscan = "on"
enable_material = "on"
enable_mergejoin = "on"
enable_nestloop = "on"
enable_seqscan = "on"
enable_sort = "on"
enable_tidscan = "on"
seq_page_cost = 1.0
random_page_cost = 4.0
cpu_tuple_cost = 0.01
cpu_index_tuple_cost = 0.005
cpu_operator_cost = 0.0025
effective_cache_size = "4GB"
geqo = "on"
geqo_threshold = 12
geqo_effort = 5
geqo_pool_size = 0
geqo_generations = 0
geqo_selection_bias = 2.0
geqo_seed = 0.0
default_statistics_target = 100
constraint_exclusion = "partition"
cursor_tuple_fraction = 0.1
from_collapse_limit = 8
join_collapse_limit = 8
log_destination = "stderr"
logging_collector = "off"
log_directory = "/opt/bldr/svc/postgresql/var/pg_log"
log_filename = "postgresql-%Y-%m-%d_%H%M%S.log"
log_file_mode = "0600"
log_truncate_on_rotation = "off"
log_rotation_age = "1d"
log_rotation_size = "10MB"
syslog_facility = "LOCAL0"
syslog_ident = "postgres"
event_source = "PostgreSQL"
client_min_messages = "notice"
log_min_messages = "warning"
log_min_error_statement = "error"
log_min_duration_statement = "1000"
debug_print_parse = "off"
debug_print_rewritten = "off"
debug_print_plan = "off"
debug_pretty_print = "on"
log_checkpoints = "off"
log_connections = "off"
log_disconnections = "off"
log_duration = "off"
log_error_verbosity = "default"
log_hostname = "off"
log_line_prefix = "%t "
log_lock_waits = "off"
log_statement = "none"
log_replication_commands = "off"
log_temp_files = "-1"
log_timezone = "GMT"
cluster_name = ""
update_process_title = "on"
track_activities = "on"
track_counts = "on"
track_io_timing = "off"
track_functions = "none"
track_activity_query_size = 1024
stats_temp_directory = "/opt/bldr/svc/postgresql/var/pg_stat_tmp"
log_parser_stats = "off"
log_planner_stats = "off"
log_executor_stats = "off"
log_statement_stats = "off"
autovacuum = "on"
log_autovacuum_min_duration = "-1"
autovacuum_max_workers = 3
autovacuum_naptime = "1min"
autovacuum_vacuum_threshold = 50
autovacuum_analyze_threshold = 50
autovacuum_vacuum_scale_factor = 0.2
autovacuum_analyze_scale_factor = 0.1
autovacuum_freeze_max_age = 200000000
autovacuum_multixact_freeze_max_age = 400000000
autovacuum_vacuum_cost_delay = "20ms"
autovacuum_vacuum_cost_limit = -1
search_path = '"$user", public'
default_tablespace = ""
temp_tablespaces = ""
check_function_bodies = "on"
default_transaction_isolation = "read committed"
default_transaction_read_only = "off"
default_transaction_deferrable = "off"
session_replication_role = "origin"
statement_timeout = 0
lock_timeout = 0
vacuum_freeze_min_age = 50000000
vacuum_freeze_table_age = 150000000
vacuum_multixact_freeze_min_age = 5000000
vacuum_multixact_freeze_table_age = 150000000
bytea_output = "hex"
xmlbinary = "base64"
xmloption = "content"
gin_fuzzy_search_limit = 0
gin_pending_list_limit = "4MB"
datestyle = "iso, mdy"
intervalstyle = "postgres"
timezone = "GMT"
timezone_abbreviations = "Default"
extra_float_digits = 0
client_encoding = "sql_ascii"
lc_messages = "C"
lc_monetary = "C"
lc_numeric = "C"
lc_time = "C"
default_text_search_config = "pg_catalog.english"
dynamic_library_path = "$libdir"
local_preload_libraries = ""
session_preload_libraries = ""
deadlock_timeout = "1s"
max_locks_per_transaction = 64
max_pred_locks_per_transaction = 64
array_nulls = "on"
backslash_quote = "safe_encoding"
default_with_oids = "off"
escape_string_warning = "on"
lo_compat_privileges = "off"
operator_precedence_warning = "off"
quote_all_identifiers = "off"
sql_inheritance = "on"
standard_conforming_strings = "on"
synchronize_seqscans = "on"
transform_null_equals = "off"
exit_on_error = "off"
restart_after_crash = "on"
include_dir = "/opt/bldr/svc/postgresql/config/conf.d"

# options for initdb.
#
# We're using `bldr` instead of `postgres` because the `bldr` user is
# created in our docker containers, the `postgres` user is not.
initdb_superuser_name = "bldr"
initdb_superuser_password = ""
initdb_pwfile = "/opt/bldr/svc/postgresql/config/pwfile"
initdb_encoding = "UTF8"
