[package]
name = "habitat_builder_worker"
version = "0.0.0"
authors = ["Adam Jacob <adam@chef.io>", "Jamie Winsor <reset@chef.io>", "Fletcher Nichol <fnichol@chef.io>", "Joshua Timberman <joshua@chef.io>", "Dave Parfitt <dparfitt@chef.io>"]
description = "Habitat-Builder Worker"
build = "../build.rs"
workspace = "../../"

[[bin]]
name = "bldr-worker"
doc = false

[dependencies]
env_logger = "*"
git2 = "*"
lazy_static = "*"
log = "*"
protobuf = "*"
toml = "*"

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]

[dependencies.zmq]
git = "https://github.com/habitat-sh/rust-zmq.git"
tag = "windows_fix_pr"

[dependencies.habitat_core]
path = "../core"

[dependencies.habitat_net]
path = "../net"

[dependencies.habitat_depot_client]
path = "../builder-depot-client"

[dependencies.habitat_builder_protocol]
path = "../builder-protocol"

[features]
functional = []
