[package]
name = "habitat-sup-client"
version = "0.0.0"
edition = "2024"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
workspace = "../../"

[dependencies]
# Please keep these alphabetized
futures = { version = "*" }
habitat_common = { path = "../common" }
habitat_core = { path = "../core" }
habitat-sup-protocol = { path = "../sup-protocol", default-features = false }
log = "0.4"
prost = "*"
rustls = "*"
termcolor = "*"
tokio = { version = "*", features = ["full"] }
tokio-util = { version = "0.7", features = ["full"] }
