[package]
name = "habitat-sup-protocol"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
build = "./build.rs"
workspace = "../../"

[dependencies]
base64 = "*"
bytes = "*"
habitat_core = { path = "../core" }
lazy_static = "*"
log = "0.4"
prost = { version = "*", features = ["prost-derive"] }
rand = { version = "0.9", features = ["thread_rng"] }
serde = {version = "*", features = ["derive"] }
tokio = { version = "*", features = ["full"] }
tokio-util = { version = "0.7", features = ["full"] }

[build-dependencies]
prost-build = "*"

[dev-dependencies]
tempfile = "*"
toml = { version = "*", features = [ "preserve_order" ] }
