[net]
worker_command_listen = "0.0.0.0"
worker_command_port = 5566
worker_heartbeat_listen = "0.0.0.0"
worker_heartbeat_port = 5567
publisher_listen = "0.0.0.0"
log_ingestion_listen = "0.0.0.0"
log_ingestion_port = 5568

[datastore]
user = "hab"
password = ""
database = "builder_jobsrv"
connection_retry_ms = 300
connection_timeout_sec = 3600

[archive]
backend = "local"
key = ""
secret = ""
endpoint = ""
bucket = ""
region = "us-east-1"
local_dir = ""
