[package]
name = "habitat_pkg_export_helm"
version = "0.0.0"
authors = ["Zeeshan Ali <zeeshan@kinvolk.io>"]
build = "../build-habitat.rs"
workspace = "../../"

[[bin]]
name = "hab-pkg-export-helm"
path = "src/main.rs"
doc = false

[dependencies]
clap = { version = "*", features = ["suggestions", "color", "unstable"] }
env_logger = "*"
habitat_core = { git = "https://github.com/habitat-sh/core.git" }
habitat_common = { path = "../common" }
habitat_pkg_export_docker = { path = "../pkg-export-docker" }
habitat_pkg_export_kubernetes = { path = "../pkg-export-kubernetes" }
# We need to lock here since v0.30.0 bumps to a version of pest that fails to build on Windows.
handlebars = { version = "0.29.1", default-features = false }
lazy_static = "*"
log = "*"
serde = "*"
serde_json = "*"
failure = "*"
failure_derive = "*"
url = "*"

[features]
default = []
functional = []
