baseURL = "/"
languageCode = "en-us"
title = "Chef Habitat Documentation"
theme = "docs-new"
themesDir = "chef-web-docs/themes"
enableGitInfo = true
pluralizeListTitles = false

disableKinds = ["taxonomy", "taxonomyTerm"]


[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
		extensions = ["hardLineBreak"]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "friendly"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  enable_search = true
  robots = ''
  menuOrder = ["infra", "workstation", "desktop", "habitat", "inspec", "automate", "legacy", "api", "extra"]
  product = "habitat"

## Main Menu ##

[[menu.main]]
title = "Chef.io"
identifier = "chef"
url = "https://www.chef.io/"
weight = 10

[[menu.main]]
title = "Learn Chef"
identifier = "learn chef"
url = "https://learn.chef.io/"
weight = 20

[[menu.main]]
title = "Blog"
identifier = "blog"
url = "https://blog.chef.io/"
weight = 30

[[menu.main]]
title = "Community"
identifier = "community"
url = "https://community.chef.io/"
weight = 40

[[menu.main]]
title = "Training"
identifier = "training"
url = "https://training.chef.io/"
weight = 50

[[menu.main]]
title = "Download"
identifier = "download"
url = "https://downloads.chef.io/"
weight = 60

###
# Chef Habitat Menu ##
###

[[menu.habitat]]
title = "Chef Habitat"
identifier = "habitat"
weight = 10

  [[menu.habitat]]
  title = "Install Habitat"
  identifier = "habitat/get_started"
  parent = "habitat"
  weight = 10

  [[menu.habitat]]
  title = "Builder"
  identifier = "habitat/builder"
  parent = "habitat"
  weight = 20

  [[menu.habitat]]
  title = "Origins"
  identifier = "habitat/origins"
  parent = "habitat"
  weight = 30

  [[menu.habitat]]
  title = "Packages"
  identifier = "habitat/packages"
  parent = "habitat"
  weight = 40

  [[menu.habitat]]
  title = "Plans"
  identifier = "habitat/plans"
  parent = "habitat"
  weight = 50

  [[menu.habitat]]
  title = "Services"
  identifier = "habitat/services"
  parent = "habitat"
  weight = 60

  [[menu.habitat]]
  title = "Supervisors"
  identifier = "habitat/supervisors"
  parent = "habitat"
  weight = 70

  [[menu.habitat]]
  title = "Studio"
  identifier = "habitat/studio"
  url = "/habitat/studio"
  parent = "habitat"
  weight = 80

  [[menu.habitat]]
  title = "Reference"
  identifier = "habitat/reference"
  parent = "habitat"
  weight = 90

  [[menu.habitat]]
  title = "Containers"
  identifier = "habitat/containers"
  parent = "habitat"
  weight = 200

  [[menu.habitat]]
  title = "Diagrams"
  identifier = "habitat/diagrams"
  parent = "habitat"
  weight = 500

