log_level = "info"
auth_token = ""
auto_publish = true
bldr_channel = "unstable"
bldr_url = "https://bldr.habitat.sh"
features_enabled = ""
airlock_enabled = true

[github]
url = "https://api.github.com"
web_url = "https://github.com"
client_id = ""
client_secret = ""
app_id = 5565
