log_level = "info"

[http]
listen = "0.0.0.0"
port = 9636

[github]
url = "https://api.github.com"
web_url = "https://github.com"
client_id = ""
client_secret = ""

[web]
app_url          = "https://willem.habitat.sh/v1"
community_url    = "https://www.habitat.sh/community"
docs_url         = "https://www.habitat.sh/docs"
environment      = "production"
friends_only     = false
source_code_url  = "https://github.com/habitat-sh/habitat"
tutorials_url    = "https://www.habitat.sh/tutorials"
www_url          = "https://www.habitat.sh"

[depot]
builds_enabled = true
events_enabled = false
