[package]
name = "habitat_depot"
version = "0.0.0"
authors = ["Adam Jacob <adam@chef.io>", "Jamie Winsor <reset@chef.io>", "Fletcher Nichol <fnichol@chef.io>", "Joshua Timberman <joshua@chef.io>", "Dave Parfitt <dparfitt@chef.io>"]
description = "Habitat-Builder package depot"
build = "../bldr-build.rs"
workspace = "../../"

[[bin]]
name = "bldr-depot"
doc = false

[dependencies]
bodyparser = "*"
env_logger = "*"
hyper = "*"
iron = "*"
libc = "*"
lazy_static = "*"
libarchive = "*"
log = "*"
mount = "*"
persistent = "*"
protobuf = "*"
r2d2 = "*"
regex = "*"
router = "*"
rust-crypto = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
time = "*"
toml = { version = "*", features = ["serde"], default-features = false }
unicase = "*"
url = "*"
urlencoded = "*"
walkdir = "*"

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]

[dependencies.habitat_builder_dbcache]
path = "../builder-dbcache"

[dependencies.habitat_builder_protocol]
path = "../builder-protocol"

[dependencies.builder_core]
path = "../builder-core"

[dependencies.habitat_core]
path = "../core"

[dependencies.habitat_net]
path = "../net"

[dependencies.r2d2_redis]
git = "https://github.com/habitat-sh/r2d2-redis.git"
branch = "habitat"

[dependencies.redis]
git = "https://github.com/habitat-sh/redis-rs"
branch = "habitat"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq"
branch = "release/v0.8"

[dev-dependencies]
url = "*"
uuid = "*"

[features]
functional = []
