language: rust
sudo: false
install:
- wget https://github.com/jedisct1/libsodium/releases/download/1.0.8/libsodium-1.0.8.tar.gz
- tar xvfz libsodium-1.0.8.tar.gz
- cd libsodium-1.0.8 && ./configure --prefix=$HOME/installed_libsodium && make && make install &&
  cd ..
- export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
- export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH
script:
- cargo build --verbose
- cargo test --verbose
- cargo test --verbose --no-default-features
- cargo doc
after_script:
- cd target/doc
- git init
- git config user.name "Travis CI"
- git config user.email "dnaq@users.noreply.github.com"
- echo "<meta http-equiv=refresh content=0;url=sodiumoxide/index.html>" > index.html
- git add .
- git commit -m "Deploy to GitHub Pages"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
env:
  global:
    - GH_REF: github.com/dnaq/sodiumoxide.git
    - secure: LFhOKKRNMdfsU4bUKLi+9ly5l0mrvnL9rS0M33aEyvCoeTiptuHsOCoSxZMk4iH5dA3IGQX+q6BjQlB5o/W4svSeOFfTvvXQ7QgqIoWqO0a9kAstVDZFTFM7xGMbI9jrihH4mHeT4dZdN779Mbnhg3tynbNapB+0ewA+cz3Wb5s=
