[package]
name = "habitat-launcher-protocol"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
build = "build.rs"
workspace = "../../"

[dependencies]
bytes = "*"
# Must use fork see https://github.com/habitat-sh/habitat/issues/7270
prost = { git = "https://github.com/dingelish/prost" }
# Must use fork see https://github.com/habitat-sh/habitat/issues/7270
prost-derive = { git = "https://github.com/dingelish/prost" }
serde = "*"
serde_derive = "*"

[build-dependencies]
# Must use fork see https://github.com/habitat-sh/habitat/issues/7270
prost-build = { git = "https://github.com/dingelish/prost" }
