[package]
name = "habitat-launcher-protocol"
version = "0.0.0"
authors = ["Jamie Winsor <reset@habitat.sh>"]
build = "build.rs"

[dependencies]
protobuf = "*"
serde = "*"
serde_derive = "*"

[build-dependencies]
pkg-config = "0.3"

[features]
protocols = []
