[package]
name = "habitat-launcher-protocol"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
build = "build.rs"
workspace = "../../"

[dependencies]
bytes = "*"
habitat_common = { path = "../common" }
prost = "*"
prost-derive = "*"
serde = "*"
serde_derive = "*"

[build-dependencies]
prost-build = "*"
