# Accept connections on the specified port, default is 6379.
# If port 0 is specified Redis will not listen on a TCP socket.
port = 6379

# TCP listen() backlog.
#
# In high requests-per-second environments you need an high backlog in order
# to avoid slow clients connections issues. Note that the Linux kernel
# will silently truncate it to the value of /proc/sys/net/core/somaxconn so
# make sure to raise both the value of somaxconn and tcp_max_syn_backlog
# in order to get the desired effect.
tcp-backlog = 511

# By default Redis listens for connections from all the network interfaces
# available on the server. It is possible to listen to just one or multiple
# interfaces using the "bind" configuration directive, followed by one or
# more IP addresses.
#
# Examples:
#
# bind = [ "192.168.1.100", "10.0.0.1" ]
# bind = [ "127.0.0.1" ]
# bind = [] - listen on all interfaces
bind = []

unixsocket = false
unixsocketperm = false
timeout = 0
tcp-keepalive = 0
loglevel = "notice"
logfile = "\"\""
syslog-enabled = ["no"]
syslog-ident = ["redis"]
syslog-facility = ["local0"]
databases = 16
stop-writes-on-bgsave-error = "yes"
rbcompression = "yes"
rbchecksum = "yes"
dbfilename = "dump.rdb"
slaveof = []
masterauth = []
slave-serve-stale-data = "yes"
slave-read-only = "yes"
repl-diskless-sync = "no"
repl-diskless-synx-delay = 5
repl-ping-slave-period = 10
repl-timeout = 60
repl-disable-tcp-nodelay = "no"
repl-backlog-size = ["1mb"]
repl-backlog-ttl = ["3600"]
slave-priority = "100"
min-slaves-to-write = false
min-slaves-max-lag = false
requirepass = []

[[save]]
sec = 900
keys = 1

[[save]]
sec = 300
keys = 10

[[save]]
sec = 60
keys = 10000

