format_version = 1
file_descriptor = "Packages to sync acceptance from production after release"

# These are all packages that we officially produce in a release.

[[x86_64-linux]]
channel = "LTS-2024"
packages = [
  "core/hab-launcher",
  "core/hab",
  "core/hab-sup",
  "core/hab-studio",
  "core/hab-plan-build",
  "core/hab-backline",
  "core/hab-pkg-export-container",
  "core/hab-pkg-export-tar",
  "core/hab-pkg-mesosize",
  "core/hab-pkg-cfize"
]

[[x86_64-linux-kernel2]]
channel = "LTS-2024"
packages = [
  "core/hab-launcher",
  "core/hab",
  "core/hab-sup",
  "core/hab-studio",
  "core/hab-plan-build",
  "core/hab-backline"
]

[[x86_64-windows]]
channel = "LTS-2024"
packages = [
  "core/windows-service",
  "core/hab-launcher",
  "core/hab",
  "core/hab-sup",
  "core/hab-studio",
  "core/hab-plan-build-ps1",
  "core/hab-pkg-export-container",
  "core/hab-pkg-export-tar"
]
