[package]
name = "habitat-eventsrv-client"
version = "0.0.0"
authors = [
  "Josh Black <raskchanky@gmail.com>",
  "Christopher Maier <cmaier@chef.io>",
  "Jamie Winsor <reset@habitat.sh>",
]
description = "Habitat EventSrv client"
workspace = "../../"

[dependencies]
clippy = {version = "*", optional = true}
byteorder = "*"
habitat-eventsrv-protocol = { git = "https://github.com/habitat-sh/protocols.git" }
lazy_static = "*"
log = "*"
protobuf = "*"
rand = "*"
time = "*"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq"
branch = "release/v0.8"

[build-dependencies]
pkg-config = "0.3"

[features]
default = []
