[package]
name = "op"
version = "0.1.0"
authors = ["Josh Black <raskchanky@gmail.com>"]
description = "Operational tools for Habitat developers"
workspace = "../../"

[dependencies]
clippy = {version = "*", optional = true}
fnv = "*"
log = "*"
habitat-builder-protocol = { path = "../builder-protocol" }
habitat_core = { path = "../core" }

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]

[features]
default = []
