---
# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: docs-notify

github:
  delete_branch_on_merge: true
  release_branch:
    - master

pipelines:
  - verify:
      description: Pull Request validation tests
      public: true

subscriptions:
  # This will update version of the Chef product Hugo module
  # that is used to build the docs when that product is promoted to stable.
  - workload: artifact_published:stable:chef-workstation:*
    actions:
    - bash:.expeditor/update_hugo_modules.sh
  - workload: artifact_published:stable:inspec:*
    actions:
      - bash:.expeditor/update_hugo_modules.sh
  - workload: project_promoted:automate:acceptance:*
    actions:
      - bash:.expeditor/update_hugo_modules.sh