[package]
name = "habitat_core"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
workspace = "../../"
build = "build.rs"

[build-dependencies]
base64 = "*"
cc = "*"

[dependencies]
base64 = "*"
blake2b_simd = "*"
chrono = "*"
dirs = "*"
dns-lookup = "*"
errno = "*"
glob = "*"
hex = "*"
lazy_static = "^1.4.0"
libc = "0.2.80"
log = "^0.4.11"
native-tls = { version = "*", features = ["vendored"] }
os_info = "*"
paste = "1.0"
pem = "*"
pin-project = "^0.4.23"
rand = "*"
regex = "*"
rcgen = "*"
rust-crypto = "*"
rustls = "*"
serde = "*"
serde_derive = "*"
serde_json = { version = "*", features = [ "preserve_order" ] }
sodiumoxide = "*"
tabwriter = "*"
tar = "*"
tempfile = "*"
thiserror = "*"
tokio = { version = "^0.2", features = ["full"] }
tokio-rustls = "^0.14" # Tokio 0.2
toml = { version = "0.5.6", features = [ "preserve_order" ] }
typemap = "*"
url = "*"
webpki = "*"
xz2 = "*"

[target.'cfg(not(windows))'.dependencies]
nix = "0.18.0"
[target.'cfg(target_os = "linux")'.dependencies]
caps = "*"

[target.'cfg(windows)'.dependencies]
ctrlc = "*"
habitat_win_users = { path = "../win-users" }
widestring = "*"
winapi = { version = "0.3.9", features = ["dpapi", "ioapiset", "namedpipeapi", "userenv", "winbase", "wincrypt", "winerror"] }
windows-acl = "*"

[dev-dependencies]
num_cpus = "*" # For doc tests
serde_test = "*"
reqwest = {version = "*", features = ["blocking"]}

[features]
default = ["supported_targets"]
functional = []
supported_targets = ["x86_64-darwin", "x86_64-linux", "x86_64-linux-kernel2", "x86_64-windows"]
x86_64-darwin = []
x86_64-linux = []
x86_64-linux-kernel2 = []
x86_64-windows = []
aarch64-linux = []
