[package]
name = "habitat_core"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
workspace = "../../"
build = "build.rs"

[build-dependencies]
base64 = "*"
cc = "*"

[dependencies]
base64 = "*"
dirs = "*"
dns-lookup = "*"
errno = "*"
hex = "*"
lazy_static = "*"
libarchive = "*"
libc = "*"
libsodium-sys = "0.0.16"
log = "*"
os_info = "*"
rand = "*"
regex = "*"
rust-crypto = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
sodiumoxide = "0.0.16"
tempfile = "*"
time = "*"
toml = { version = "*", default-features = false }
typemap = "*"
url = "*"

[target.'cfg(not(windows))'.dependencies]
users = "*"

[target.'cfg(target_os = "linux")'.dependencies]
caps = "*"

[target.'cfg(windows)'.dependencies]
ctrlc = "*"
habitat_win_users = { path = "../win-users" }
widestring = "*"
winapi = { version = "*", features = ["dpapi", "ioapiset", "namedpipeapi", "userenv", "winbase", "wincrypt", "winerror"] }
windows-acl = "*"

[dev-dependencies]
num_cpus = "*" # For doc tests

[features]
default = ["supported_targets"]
functional = []
supported_targets = ["x86_64-darwin", "x86_64-linux", "x86_64-linux-kernel2", "x86_64-windows"]
x86_64-darwin = []
x86_64-linux = []
x86_64-linux-kernel2 = []
x86_64-windows = []
aarch64-linux = []
