[package]
name = "habitat_builder_api"
version = "0.0.0"
authors = ["Adam Jacob <adam@chef.io>", "Jamie Winsor <reset@chef.io>", "Fletcher Nichol <fnichol@chef.io>", "Joshua Timberman <joshua@chef.io>", "Dave Parfitt <dparfitt@chef.io>"]
description = "Habitat-Builder HTTP API gateway"
build = "build.rs"
workspace = "../../"

[[bin]]
name = "bldr-api"
doc = false

[dependencies]
bodyparser = "*"
env_logger = "*"
hyper = "*"
iron = "*"
lazy_static = "*"
log = "*"
mount = "*"
persistent = "*"
protobuf = "*"
router = "*"
rustc-serialize = "*"
serde = "*"
serde_json = "*"
toml = "*"
unicase = "*"

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]

# JW TODO: Move back to a crate dependency once https://github.com/iron/staticfile/pull/91 has
# been merged into master and released
[dependencies.staticfile]
git = "https://github.com/onur/staticfile"
branch = "iron-0.5"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq"
branch = "release/v0.8"

[dependencies.habitat_core]
path = "../core"

[dependencies.habitat_depot]
path = "../builder-depot"

[dependencies.habitat_builder_protocol]
path = "../builder-protocol"

[dependencies.habitat_net]
path = "../net"

[dependencies.redis]
git = "https://github.com/habitat-sh/redis-rs"
branch = "habitat"

[build-dependencies]
serde_codegen = "*"

[replace]
"redis:0.7.0" = { git = 'https://github.com/habitat-sh/redis-rs', branch = 'habitat' }

[features]
functional = []
