log_level = "info"
shards = []

[permissions]
app_install_id = 56215
admin_team = 1995301
build_worker_teams = [1995301, 1996256]
early_access_teams = [1995301]

[datastore]
user = "hab"
password = ""
database = "builder_sessionsrv"
connection_retry_ms = 300
connection_timeout_sec = 3600

[github]
url = "https://api.github.com"
web_url = "https://github.com"
client_id = ""
client_secret = ""
app_id = 5565
